### ISSUE TITLE
Error RepositoryNotFoundError: 404 Client Error when Setup project ressources

### ISSUE THREAD

**Issue by perspectiva-solution** [huggingface/data-is-better-together#56]
I got an error when I **Setup project ressources**.
I gave all the written power to Hub token (FINEGRAINED).

![Capture d'écran 2024-04-29 234910](https://github.com/huggingface/data-is-better-together/assets/168289573/5446939a-9da1-4a44-8829-f0c622575e93)

When I use the space, it is still link to the demo config and I got an error of credential when I wanted to push seed dataset.

```
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Network URL: http://10.25.10.238:8501
  External URL: http://34.230.254.100:8501

2024-04-29 23:46:01.712 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/repos/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/user/app/pages/2_👩🏼‍🔬 Describe Domain.py", line 255, in <module>
    push_dataset_to_hub(
  File "/home/user/app/hub.py", line 62, in push_dataset_to_hub
    setup_dataset_on_hub(repo_id=repo_id, hub_token=hub_token)
  File "/home/user/app/hub.py", line 44, in setup_dataset_on_hub
    hf_api.create_repo(
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3360, in create_repo
    hf_raise_for_status(r)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 371, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/repos/create (Request ID: Root=1-66301519-1606dc2953cd0a574ae923b5;ee20af56-6b8f-4cd9-9c6f-d6156d0f84ee)

Invalid username or password.
```

Is there a config I need to change?

**Comment by perspectiva-solution** [comment]
The token does not work with Fine grained option. Use  `write` token with your user account and not your organization.
